### ISSUE TITLE
How to evaluate the performance of a SPF algorithm?

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#4]
To answer this question, you can:

- search Internet
- read paper
- study relevant chapters in the classic textbook

The output should be in the second weekly report https://github.com/swangcs/spf_perf/wiki/weeklyreport2.

**Comment by GabLah** [comment]
Mariusz Gła ̨bowski, Bartosz Musznicki, Przemysław Nowak and Piotr Zwierzykowski，Efficiency Evaluation of Shortest Path Algorithms [https://www.thinkmind.org/download.php?articleid=aict_2013_7_30_10105](url)
1.	Running time - custom, multistage, random
2.	The possibility of the worst case occurs 
3.	The time needed for the graph

**Comment by GabLah** [comment]
Soumen Ghosh and Nayeem Mehedi and Sahariar Khandoker and Sabbir Aanwar，Comparative analysis between SPF and BAR algorithm in SDN unicast network [https://pdfs.semanticscholar.org/4126/467fb5b2519eee3bd2dccc349291d1e8162d.pdf](url)
Based on the  Software Defined Networking 
1.	All sum of the cost
2.	The data loss percentage
3.	The latency of network
4.	The links were given the same bandwidth：
     1.	Average hop count 
     2.	Communication cost of a request
     3.	Average unsatisfied request rate
     4.	The average bandwidth satisfaction rate
     5.	Average link utilization

**Comment by GabLah** [comment]
[https://www.researchgate.net/post/How_can_I_measure_the_performance_of_an_algorithm](url)
Measuring Performance of Algorithms

Two aspects of algorithmic performance：
Time：
1.	Instructions take time
2.	How fast does the algorithm perform
3.	What affects its runtime
Space:
1.	Data structures take space
2.	What kind of data structure can be used
3.	How does the choice of data structure affect the runtime

Algorithms cannot be compared by running them on computers. Run time is system dependent.
Generally concerned with how the amount of work varies with the data.

**Comment by GabLah** [comment]
[https://en.wikipedia.org/wiki/Shortest_path_problem](url) Shortest path problem

Cherkassky, Boris V.; Goldberg, Andrew V.; Radzik, Tomasz (1996). "Shortest paths algorithms: theory and experimental evaluation". Mathematical Programming. Ser. A. 73 (2): 129–174. doi:10.1016/0025-5610(95)00021-6. MR 1392160. [http://ftp.cs.stanford.edu/cs/theory/pub/goldberg/sp-alg.ps.Z](url)

1.	Robustness (some algorithms previously considered robust may fail dramatically)
2.	Dependence of the performance on the network structure 
3.	The arc cost distribution
4.	Whether small changes may drastically decrease the performance of an algorithm —— robust / security
5.	The difference in the running time of some implementations is due to some different work. ( whether the performance is identical or not)
6.	The potential for large memory requirements
7.	The length of edges: negative or nonnegative
